### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by duansheyu** [tongqii/hotlist#15]
yarn run v1.22.4
$ react-scripts start
/www/wwwroot/hotlist/node_modules/react-dev-utils/WebpackDevServerUtils.js:167
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/wwwroot/hotlist/node_modules/react-scripts/scripts/start.js:45:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
显示这样

**Comment by tongqii** [comment]
我把代码更新到最新了，你同步一下，试试有没有解决你的问题
